import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./styles/index.scss";

const inter = Montserrat({ subsets: ["latin", "cyrillic"] }); 

export const metadata: Metadata = {
  title: "Stroy depot",
  description: "Generated by Nurzh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
